#!/bin/bash
# Script to create commands for Apertif ATDB
# Automatic generation script by V.A. Moss 04/10/2018
# Last updated by V.A. Moss 07/06/2019
# Schedule generated by moss: 2019-06-07 11:36:38.736534 UTC

atdb_service --field_name=B0531+21 --field_ra=83.633115 --field_dec=22.014503 --field_beam=0 --starttime='2019-05-28 08:20:00' --duration=300 --pattern=square_39p1 --integration_factor=30 --observing_mode=arts_sc4_survey --telescopes=23456789 --central_frequency=1370 --data_dir=/data2/output/ --irods_coll=arts_main/arts_sc4 --science_mode=TAB --operation=specification --atdb_host=prod --process_triggers   

atdb_service --field_name=R2 --field_ra=65.500000 --field_dec=73.733333 --field_beam=0 --starttime='2019-05-28 08:30:00' --duration=10800 --pattern=square_39p1 --integration_factor=30 --observing_mode=arts_sc4_survey --telescopes=23456789 --central_frequency=1370 --data_dir=/data2/output/ --irods_coll=arts_main/arts_sc4 --science_mode=TAB --operation=specification --atdb_host=prod --process_triggers   

atdb_service --field_name=R2 --field_ra=65.500000 --field_dec=73.733333 --field_beam=0 --starttime='2019-05-28 11:38:00' --duration=10800 --pattern=square_39p1 --integration_factor=30 --observing_mode=arts_sc4_survey --telescopes=23456789 --central_frequency=1370 --data_dir=/data2/output/ --irods_coll=arts_main/arts_sc4 --science_mode=TAB --operation=specification --atdb_host=prod --process_triggers   

atdb_service --field_name=R2 --field_ra=65.500000 --field_dec=73.733333 --field_beam=0 --starttime='2019-05-28 14:41:00' --duration=8340 --pattern=square_39p1 --integration_factor=30 --observing_mode=arts_sc4_survey --telescopes=23456789 --central_frequency=1370 --data_dir=/data2/output/ --irods_coll=arts_main/arts_sc4 --science_mode=TAB --operation=specification --atdb_host=prod --process_triggers   

atdb_service --field_name=R1 --field_ra=82.994583 --field_dec=33.147900 --field_beam=0 --starttime='2019-05-28 17:10:00' --duration=4800 --pattern=square_39p1 --integration_factor=30 --observing_mode=arts_sc4_survey --telescopes=23456789 --central_frequency=1370 --data_dir=/data2/output/ --irods_coll=arts_main/arts_sc4 --science_mode=TAB --operation=specification --atdb_host=prod --process_triggers   

atdb_service --field_name=3C286drift00 --field_ha=-29.297215 --field_dec=30.509156 --field_beam=0 --starttime='2019-05-28 18:40:00' --duration=477 --pattern=square_39p1 --integration_factor=30 --observing_mode=arts_sc4_survey --telescopes=23456789 --central_frequency=1370 --data_dir=/data2/output/ --irods_coll=arts_main/arts_sc4 --science_mode=TAB --operation=specification --atdb_host=prod --process_triggers   

atdb_service --field_name=3C286drift0107 --field_ha=-26.548659 --field_dec=30.509156 --field_beam=7 --starttime='2019-05-28 18:50:57' --duration=1314 --pattern=square_39p1 --integration_factor=30 --observing_mode=arts_sc4_survey --telescopes=23456789 --central_frequency=1370 --data_dir=/data2/output/ --irods_coll=arts_main/arts_sc4 --science_mode=TAB --operation=specification --atdb_host=prod --process_triggers   

atdb_service --field_name=3C286drift0814 --field_ha=-20.308464 --field_dec=30.509156 --field_beam=14 --starttime='2019-05-28 19:15:51' --duration=1313 --pattern=square_39p1 --integration_factor=30 --observing_mode=arts_sc4_survey --telescopes=23456789 --central_frequency=1370 --data_dir=/data2/output/ --irods_coll=arts_main/arts_sc4 --science_mode=TAB --operation=specification --atdb_host=prod --process_triggers   

atdb_service --field_name=3C286drift1520 --field_ha=-14.068270 --field_dec=30.509156 --field_beam=20 --starttime='2019-05-28 19:40:44' --duration=1175 --pattern=square_39p1 --integration_factor=30 --observing_mode=arts_sc4_survey --telescopes=23456789 --central_frequency=1370 --data_dir=/data2/output/ --irods_coll=arts_main/arts_sc4 --science_mode=TAB --operation=specification --atdb_host=prod --process_triggers   

atdb_service --field_name=3C286drift2126 --field_ha=-8.410015 --field_dec=30.509156 --field_beam=26 --starttime='2019-05-28 20:03:19' --duration=1174 --pattern=square_39p1 --integration_factor=30 --observing_mode=arts_sc4_survey --telescopes=23456789 --central_frequency=1370 --data_dir=/data2/output/ --irods_coll=arts_main/arts_sc4 --science_mode=TAB --operation=specification --atdb_host=prod --process_triggers   

atdb_service --field_name=3C286drift2732 --field_ha=-2.751760 --field_dec=30.509156 --field_beam=32 --starttime='2019-05-28 20:25:53' --duration=1174 --pattern=square_39p1 --integration_factor=30 --observing_mode=arts_sc4_survey --telescopes=23456789 --central_frequency=1370 --data_dir=/data2/output/ --irods_coll=arts_main/arts_sc4 --science_mode=TAB --operation=specification --atdb_host=prod --process_triggers   

atdb_service --field_name=3C286drift3339 --field_ha=2.906494 --field_dec=30.509156 --field_beam=39 --starttime='2019-05-28 20:48:27' --duration=1314 --pattern=square_39p1 --integration_factor=30 --observing_mode=arts_sc4_survey --telescopes=23456789 --central_frequency=1370 --data_dir=/data2/output/ --irods_coll=arts_main/arts_sc4 --science_mode=TAB --operation=specification --atdb_host=prod --process_triggers   

atdb_service --field_name=B0950+08 --field_ra=148.288878 --field_dec=7.926686 --field_beam=0 --starttime='2019-05-28 21:23:40' --duration=300 --pattern=square_39p1 --integration_factor=30 --observing_mode=arts_sc4_survey --telescopes=23456789 --central_frequency=1370 --data_dir=/data2/output/ --irods_coll=arts_main/arts_sc4 --science_mode=TAB --operation=specification --atdb_host=prod --process_triggers   

atdb_service --field_name=T1611+3848 --field_ra=242.775000 --field_dec=38.808889 --field_beam=0 --starttime='2019-05-28 21:37:00' --duration=10800 --pattern=square_39p1 --integration_factor=30 --observing_mode=arts_sc4_survey --telescopes=23456789 --central_frequency=1370 --data_dir=/data2/output/ --irods_coll=arts_main/arts_sc4 --science_mode=TAB --operation=specification --atdb_host=prod --process_triggers   

atdb_service --field_name=T1829+4606 --field_ra=277.295833 --field_dec=46.105000 --field_beam=0 --starttime='2019-05-29 00:42:01' --duration=10800 --pattern=square_39p1 --integration_factor=30 --observing_mode=arts_sc4_survey --telescopes=23456789 --central_frequency=1370 --data_dir=/data2/output/ --irods_coll=arts_main/arts_sc4 --science_mode=TAB --operation=specification --atdb_host=prod --process_triggers   

atdb_service --field_name=T2138+1921 --field_ra=324.587500 --field_dec=19.351944 --field_beam=0 --starttime='2019-05-29 03:47:44' --duration=10800 --pattern=square_39p1 --integration_factor=30 --observing_mode=arts_sc4_survey --telescopes=23456789 --central_frequency=1370 --data_dir=/data2/output/ --irods_coll=arts_main/arts_sc4 --science_mode=TAB --operation=specification --atdb_host=prod --process_triggers   

