#!/bin/bash
# Script to create commands for Apertif ATDB
# Automatic generation script by V.A. Moss 04/10/2018
# Last updated by V.A. Moss 07/06/2019
# Schedule generated by moss: 2019-06-07 11:35:54.397843 UTC

