#!/bin/bash
# Script to create commands for Apertif ATDB
# Automatic generation script by V.A. Moss 04/10/2018
# Last updated by V.A. Moss 07/06/2019
# Schedule generated by moss: 2019-06-07 11:37:02.116125 UTC

atdb_service --field_name=3C286_0 --field_ra=202.784533 --field_dec=30.509153 --field_beam=0 --starttime='2019-05-29 15:40:00' --endtime='2019-05-29 15:41:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_1 --field_ra=202.784533 --field_dec=30.509153 --field_beam=1 --starttime='2019-05-29 15:43:00' --endtime='2019-05-29 15:44:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_2 --field_ra=202.784533 --field_dec=30.509153 --field_beam=2 --starttime='2019-05-29 15:46:00' --endtime='2019-05-29 15:47:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_3 --field_ra=202.784533 --field_dec=30.509153 --field_beam=3 --starttime='2019-05-29 15:49:00' --endtime='2019-05-29 15:50:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_4 --field_ra=202.784533 --field_dec=30.509153 --field_beam=4 --starttime='2019-05-29 15:52:00' --endtime='2019-05-29 15:53:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_5 --field_ra=202.784533 --field_dec=30.509153 --field_beam=5 --starttime='2019-05-29 15:55:00' --endtime='2019-05-29 15:56:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_6 --field_ra=202.784533 --field_dec=30.509153 --field_beam=6 --starttime='2019-05-29 15:58:00' --endtime='2019-05-29 15:59:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_7 --field_ra=202.784533 --field_dec=30.509153 --field_beam=7 --starttime='2019-05-29 16:01:00' --endtime='2019-05-29 16:02:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_8 --field_ra=202.784533 --field_dec=30.509153 --field_beam=8 --starttime='2019-05-29 16:04:00' --endtime='2019-05-29 16:05:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_9 --field_ra=202.784533 --field_dec=30.509153 --field_beam=9 --starttime='2019-05-29 16:07:00' --endtime='2019-05-29 16:08:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_10 --field_ra=202.784533 --field_dec=30.509153 --field_beam=10 --starttime='2019-05-29 16:10:00' --endtime='2019-05-29 16:11:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_11 --field_ra=202.784533 --field_dec=30.509153 --field_beam=11 --starttime='2019-05-29 16:13:00' --endtime='2019-05-29 16:14:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_12 --field_ra=202.784533 --field_dec=30.509153 --field_beam=12 --starttime='2019-05-29 16:16:00' --endtime='2019-05-29 16:17:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_13 --field_ra=202.784533 --field_dec=30.509153 --field_beam=13 --starttime='2019-05-29 16:19:00' --endtime='2019-05-29 16:20:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_14 --field_ra=202.784533 --field_dec=30.509153 --field_beam=14 --starttime='2019-05-29 16:22:00' --endtime='2019-05-29 16:23:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_15 --field_ra=202.784533 --field_dec=30.509153 --field_beam=15 --starttime='2019-05-29 16:25:00' --endtime='2019-05-29 16:26:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_16 --field_ra=202.784533 --field_dec=30.509153 --field_beam=16 --starttime='2019-05-29 16:28:00' --endtime='2019-05-29 16:29:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_17 --field_ra=202.784533 --field_dec=30.509153 --field_beam=17 --starttime='2019-05-29 16:31:00' --endtime='2019-05-29 16:32:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_18 --field_ra=202.784533 --field_dec=30.509153 --field_beam=18 --starttime='2019-05-29 16:34:00' --endtime='2019-05-29 16:35:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_19 --field_ra=202.784533 --field_dec=30.509153 --field_beam=19 --starttime='2019-05-29 16:37:00' --endtime='2019-05-29 16:38:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_20 --field_ra=202.784533 --field_dec=30.509153 --field_beam=20 --starttime='2019-05-29 16:40:00' --endtime='2019-05-29 16:41:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_21 --field_ra=202.784533 --field_dec=30.509153 --field_beam=21 --starttime='2019-05-29 16:43:00' --endtime='2019-05-29 16:44:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_22 --field_ra=202.784533 --field_dec=30.509153 --field_beam=22 --starttime='2019-05-29 16:46:00' --endtime='2019-05-29 16:47:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_23 --field_ra=202.784533 --field_dec=30.509153 --field_beam=23 --starttime='2019-05-29 16:49:00' --endtime='2019-05-29 16:50:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_24 --field_ra=202.784533 --field_dec=30.509153 --field_beam=24 --starttime='2019-05-29 16:52:00' --endtime='2019-05-29 16:53:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_25 --field_ra=202.784533 --field_dec=30.509153 --field_beam=25 --starttime='2019-05-29 16:55:00' --endtime='2019-05-29 16:56:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_26 --field_ra=202.784533 --field_dec=30.509153 --field_beam=26 --starttime='2019-05-29 16:58:00' --endtime='2019-05-29 16:59:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_27 --field_ra=202.784533 --field_dec=30.509153 --field_beam=27 --starttime='2019-05-29 17:01:00' --endtime='2019-05-29 17:02:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_28 --field_ra=202.784533 --field_dec=30.509153 --field_beam=28 --starttime='2019-05-29 17:04:00' --endtime='2019-05-29 17:05:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_29 --field_ra=202.784533 --field_dec=30.509153 --field_beam=29 --starttime='2019-05-29 17:07:00' --endtime='2019-05-29 17:08:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_30 --field_ra=202.784533 --field_dec=30.509153 --field_beam=30 --starttime='2019-05-29 17:10:00' --endtime='2019-05-29 17:11:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_31 --field_ra=202.784533 --field_dec=30.509153 --field_beam=31 --starttime='2019-05-29 17:13:00' --endtime='2019-05-29 17:14:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_32 --field_ra=202.784533 --field_dec=30.509153 --field_beam=32 --starttime='2019-05-29 17:16:00' --endtime='2019-05-29 17:17:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_33 --field_ra=202.784533 --field_dec=30.509153 --field_beam=33 --starttime='2019-05-29 17:19:00' --endtime='2019-05-29 17:20:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_34 --field_ra=202.784533 --field_dec=30.509153 --field_beam=34 --starttime='2019-05-29 17:22:00' --endtime='2019-05-29 17:23:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_35 --field_ra=202.784533 --field_dec=30.509153 --field_beam=35 --starttime='2019-05-29 17:25:00' --endtime='2019-05-29 17:26:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_36 --field_ra=202.784533 --field_dec=30.509153 --field_beam=36 --starttime='2019-05-29 17:28:00' --endtime='2019-05-29 17:29:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_37 --field_ra=202.784533 --field_dec=30.509153 --field_beam=37 --starttime='2019-05-29 17:31:00' --endtime='2019-05-29 17:32:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_38 --field_ra=202.784533 --field_dec=30.509153 --field_beam=38 --starttime='2019-05-29 17:34:00' --endtime='2019-05-29 17:35:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C286_39 --field_ra=202.784533 --field_dec=30.509153 --field_beam=39 --starttime='2019-05-29 17:37:00' --endtime='2019-05-29 17:38:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

