#!/bin/bash
# Script to create commands for Apertif ATDB
# Automatic generation script by V.A. Moss 04/10/2018
# Last updated by V.A. Moss 07/06/2019
# Schedule generated by moss: 2019-06-07 11:37:24.691438 UTC

atdb_service --field_name=CygAdrift-79 --field_ha=-81.787381 --field_dec=42.105232 --field_beam=0 --starttime='2019-05-27 21:35:00' --endtime='2019-05-27 21:55:46' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift-72 --field_ha=-76.075298 --field_dec=42.003895 --field_beam=0 --starttime='2019-05-27 21:57:46' --endtime='2019-05-27 22:18:34' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift-66 --field_ha=-70.355593 --field_dec=41.902558 --field_beam=0 --starttime='2019-05-27 22:20:34' --endtime='2019-05-27 22:41:24' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift-60 --field_ha=-64.628226 --field_dec=41.801221 --field_beam=0 --starttime='2019-05-27 22:43:24' --endtime='2019-05-27 23:04:15' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift-54 --field_ha=-58.893159 --field_dec=41.699884 --field_beam=0 --starttime='2019-05-27 23:06:15' --endtime='2019-05-27 23:27:09' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift-48 --field_ha=-53.150351 --field_dec=41.598547 --field_beam=0 --starttime='2019-05-27 23:29:09' --endtime='2019-05-27 23:50:04' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift-42 --field_ha=-47.399765 --field_dec=41.497210 --field_beam=0 --starttime='2019-05-27 23:52:04' --endtime='2019-05-28 00:13:01' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift-36 --field_ha=-41.947672 --field_dec=41.395873 --field_beam=0 --starttime='2019-05-28 00:15:01' --endtime='2019-05-28 00:36:01' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift-30 --field_ha=-36.181868 --field_dec=41.294536 --field_beam=0 --starttime='2019-05-28 00:38:01' --endtime='2019-05-28 00:59:02' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift-24 --field_ha=-30.408167 --field_dec=41.193199 --field_beam=0 --starttime='2019-05-28 01:01:02' --endtime='2019-05-28 01:22:04' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift-18 --field_ha=-24.626530 --field_dec=41.091862 --field_beam=0 --starttime='2019-05-28 01:24:04' --endtime='2019-05-28 01:45:09' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift-12 --field_ha=-19.145077 --field_dec=40.990525 --field_beam=0 --starttime='2019-05-28 01:47:09' --endtime='2019-05-28 02:05:48' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift-6 --field_ha=-13.965921 --field_dec=40.889188 --field_beam=0 --starttime='2019-05-28 02:07:48' --endtime='2019-05-28 02:26:29' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift+00 --field_ha=-8.779649 --field_dec=40.787851 --field_beam=0 --starttime='2019-05-28 02:28:29' --endtime='2019-05-28 02:47:11' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift+06 --field_ha=-3.586222 --field_dec=40.686514 --field_beam=0 --starttime='2019-05-28 02:49:11' --endtime='2019-05-28 03:07:55' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift+12 --field_ha=1.924442 --field_dec=40.585177 --field_beam=0 --starttime='2019-05-28 03:09:55' --endtime='2019-05-28 03:28:40' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift+18 --field_ha=7.132764 --field_dec=40.483840 --field_beam=0 --starttime='2019-05-28 03:30:40' --endtime='2019-05-28 03:49:28' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift+24 --field_ha=12.348352 --field_dec=40.382503 --field_beam=0 --starttime='2019-05-28 03:51:28' --endtime='2019-05-28 04:10:17' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift+30 --field_ha=17.571245 --field_dec=40.281166 --field_beam=0 --starttime='2019-05-28 04:12:17' --endtime='2019-05-28 04:31:08' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift+36 --field_ha=22.489506 --field_dec=40.179829 --field_beam=0 --starttime='2019-05-28 04:33:08' --endtime='2019-05-28 04:52:01' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift+42 --field_ha=27.726632 --field_dec=40.078492 --field_beam=0 --starttime='2019-05-28 04:54:01' --endtime='2019-05-28 05:12:55' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift+48 --field_ha=32.971172 --field_dec=39.977155 --field_beam=0 --starttime='2019-05-28 05:14:55' --endtime='2019-05-28 05:33:51' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift+54 --field_ha=38.223166 --field_dec=39.875818 --field_beam=0 --starttime='2019-05-28 05:35:51' --endtime='2019-05-28 05:54:49' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift+60 --field_ha=43.796588 --field_dec=39.774481 --field_beam=0 --starttime='2019-05-28 05:56:49' --endtime='2019-05-28 06:18:20' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift+66 --field_ha=49.693696 --field_dec=39.673144 --field_beam=0 --starttime='2019-05-28 06:20:20' --endtime='2019-05-28 06:41:52' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift+72 --field_ha=55.599374 --field_dec=39.571807 --field_beam=0 --starttime='2019-05-28 06:43:52' --endtime='2019-05-28 07:05:27' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=CygAdrift+79 --field_ha=61.513664 --field_dec=39.470470 --field_beam=0 --starttime='2019-05-28 07:07:27' --endtime='2019-05-28 07:29:03' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

