#!/bin/bash
# Script to create commands for Apertif ATDB
# Automatic generation script by V.A. Moss 04/10/2018
# Last updated by V.A. Moss 07/06/2019
# Schedule generated by moss: 2019-06-07 11:37:35.477509 UTC

atdb_service --field_name=3C48drift+00 --field_ha=-79.394712 --field_dec=33.159759 --field_beam=0 --starttime='2019-06-03 03:00:00' --endtime='2019-06-03 03:19:07' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C48drift-60 --field_ha=29.715754 --field_dec=33.159759 --field_beam=7 --starttime='2019-06-03 03:21:07' --endtime='2019-06-03 03:56:20' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C48drift-36 --field_ha=-70.065129 --field_dec=33.159759 --field_beam=14 --starttime='2019-06-03 03:58:20' --endtime='2019-06-03 04:33:33' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C48drift-12 --field_ha=39.045467 --field_dec=33.159759 --field_beam=20 --starttime='2019-06-03 04:35:33' --endtime='2019-06-03 05:08:05' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C48drift+12 --field_ha=-61.408237 --field_dec=33.159759 --field_beam=26 --starttime='2019-06-03 05:10:05' --endtime='2019-06-03 05:42:37' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C48drift+36 --field_ha=47.702525 --field_dec=33.159759 --field_beam=32 --starttime='2019-06-03 05:44:37' --endtime='2019-06-03 06:17:09' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

atdb_service --field_name=3C48drift+60 --field_ha=-52.751358 --field_dec=33.159759 --field_beam=39 --starttime='2019-06-03 06:19:09' --endtime='2019-06-03 06:54:22' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod  --end_band=24  

