#!/bin/bash
# Script to create commands for Apertif ATDB
# Automatic generation script by V.A. Moss 04/10/2018
# Last updated by V.A. Moss 07/06/2019
# Schedule generated by moss: 2019-06-07 12:34:44.055216 UTC

atdb_service --field_name=3C286 --field_ra=202.784533 --field_dec=30.509155 --field_beam=0 --starttime='2019-05-31 15:45:00' --endtime='2019-05-31 15:46:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod --end_band=24 --delay_center_offset=[0.5,0.0] 

atdb_service --field_name=3C286 --field_ra=202.784533 --field_dec=30.509155 --field_beam=0 --starttime='2019-05-31 15:48:00' --endtime='2019-05-31 15:49:00' --pattern=central_element_beams_x --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod --end_band=24 --delay_center_offset=[0.5,0.0] 

atdb_service --field_name=3C286_11 --field_ra=202.784533 --field_dec=30.509155 --field_beam=11 --starttime='2019-05-31 15:51:00' --endtime='2019-05-31 15:52:00' --pattern=square_39p1 --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod --end_band=24 --delay_center_offset=[0.5,0.0] 

atdb_service --field_name=3C286_11 --field_ra=202.784533 --field_dec=30.509155 --field_beam=11 --starttime='2019-05-31 15:54:00' --endtime='2019-05-31 15:55:00' --pattern=central_element_beams_x --observing_mode=imaging --integration_factor=10 --telescopes=23456789ABCD --central_frequency=1370 --data_dir=/data/apertif/ --operation=specification --atdb_host=prod --end_band=24 --delay_center_offset=[0.5,0.0] 

